---
name: "🐛 Bug Report"
description: "Something isn't working as expected 🤔"
labels: bug
body:
  - type: checkboxes
    id: search
    attributes:
      label: Please avoid duplicates
      options:
        - label: I checked [all open bugs](https://github.com/gr2m/semantic-release-plugin-github-breaking-version-tag/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and none of them matched my problem.
          required: true
  - type: input
    id: testcase
    attributes:
      label: Reproducible test case
      description: |
        If possible, please create a minimal test case that reproduces your problem. For TypeScript-only problems, you can create TypeScript playground ([example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAelWgFMyAoAgVwDt1gIu4wAM4BlGFGBcA5gAoA7gAsAhjABccIeMlSAlIlytWjLprjUM2eAF44XJnJQ1LMnYeOmkAExVK4+G0pySjhmTjgAdFBMAI4cTJoyZADiAKIAKnB0ZK6sdHRwFDBCALRMAB5gTOilUMRQcABWHKa+nkwgEKzCYhLSMt4wSuGeEPEA+lwQMGPlwjA6QA)). For code-related issues, please create a RunKit Notebook ([example](https://runkit.com/gr2m/octokit-auth-oauth-app-js-178/1.0.0)).
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Please share the versions of `semantic-release-plugin-github-breaking-version-tag` and Node that you are using.
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Please share any other relevant information not mentioned above. What did you expect to happen? What do you think the problem might be?
  - type: checkboxes
    id: contributor
    attributes:
      label: Would you be interested in contributing a fix?
      options:
        - label: "yes"
