blank_issues_enabled: false
contact_links:
  - name: 🆘 I need Help
    url: https://github.com/gr2m/semantic-release-plugin-github-breaking-version-tag/discussions
    about: Got a question? An idea? Feedback? Start here.
